/**
 * Every page of the Kassenta brochure, in English and German.
 *
 * One file rather than two so a screen cannot exist in one language and be
 * quietly missing from the other — the build fails loudly if `de` is absent.
 *
 * `shot` is a filename in docs/brochure/shots/. `portrait: true` renders the
 * image in a phone frame beside the text instead of full width.
 */

const LINKS = {
  site: "https://kassenta.com/",
  desktop: "https://kassenta.com/app/",
  pos: "https://play.google.com/store/apps/details?id=tech.barmagly.pos",
  order: "https://play.google.com/store/apps/details?id=com.barmagly.customer",
  mail: "info@kassenta.com",
};

const meta = {
  en: {
    lang: "en",
    title: "Kassenta",
    subtitle: "The complete point of sale, online ordering and delivery system",
    coverNote: "Product guide and screen reference",
    tocTitle: "Contents",
    linksTitle: "Where to find Kassenta",
    controlsLabel: "On this screen",
    pageWord: "Page",
    sectionWord: "Section",
  },
  de: {
    lang: "de",
    title: "Kassenta",
    subtitle: "Das komplette Kassen-, Onlinebestell- und Liefersystem",
    coverNote: "Produkthandbuch und Bildschirmreferenz",
    tocTitle: "Inhalt",
    linksTitle: "Wo Sie Kassenta finden",
    controlsLabel: "Auf diesem Bildschirm",
    pageWord: "Seite",
    sectionWord: "Abschnitt",
  },
};

/** The opening spread: what the system is and who it is for. */
const intro = {
  en: {
    heading: "One system, from the counter to the doorstep",
    lead:
      "Kassenta is a complete retail and hospitality system. It runs the till, the kitchen, " +
      "the stockroom, the online shop and the delivery fleet from a single account, so a " +
      "sale taken at the counter, an order placed on a phone and a driver on the road all " +
      "sit in the same set of books.",
    body: [
      "It was not built for one kind of shop. A pizzeria needs sizes, toppings and a " +
        "kitchen display. A supermarket needs barcodes, suppliers and stock counts. A " +
        "pharmacy needs strict records. A café needs speed above all. Kassenta ships " +
        "presets for each and lets a shop change its mind later.",
      "Everything runs on hardware a shop already owns. The till is an Android tablet, " +
        "the customer app is an ordinary phone app, and the whole system also opens in a " +
        "browser on any laptop or desktop. There is no proprietary terminal to buy.",
    ],
    industriesTitle: "Built for",
    industries: [
      ["Restaurants", "Tables, courses, kitchen tickets, sizes and modifiers"],
      ["Cafés and bakeries", "Fast repeat orders, counter service, shift handover"],
      ["Supermarkets", "Barcode scanning, suppliers, purchase orders, stock counts"],
      ["Pharmacies", "Controlled records, precise stock, audit trail"],
      ["Takeaway and delivery", "Zones, fees, drivers, live tracking"],
      ["Any retail counter", "Products, prices, receipts, reports"],
    ],
    platformTitle: "Three ways in, one set of data",
    platforms: [
      ["Kassenta POS", "Android tablet or phone. The till, stock, staff and reports.", LINKS.pos],
      ["Kassenta Order", "Android phone. Your customers browse, order and track.", LINKS.order],
      ["Desktop and laptop", "The same system in any browser. Nothing to install.", LINKS.desktop],
    ],
  },
  de: {
    heading: "Ein System, von der Theke bis an die Haustür",
    lead:
      "Kassenta ist ein komplettes System für Handel und Gastronomie. Es steuert die Kasse, " +
      "die Küche, das Lager, den Onlineshop und die Lieferflotte über ein einziges Konto. " +
      "Ein Verkauf an der Theke, eine Bestellung per Handy und ein Fahrer unterwegs stehen " +
      "damit in derselben Buchführung.",
    body: [
      "Es wurde nicht für eine einzige Art von Geschäft gebaut. Eine Pizzeria braucht " +
        "Grössen, Beläge und einen Küchenbildschirm. Ein Supermarkt braucht Barcodes, " +
        "Lieferanten und Inventuren. Eine Apotheke braucht lückenlose Aufzeichnungen. Ein " +
        "Café braucht vor allem Tempo. Kassenta liefert für jedes eine Voreinstellung — und " +
        "lässt den Betrieb später umentscheiden.",
      "Alles läuft auf Geräten, die ein Geschäft ohnehin besitzt. Die Kasse ist ein " +
        "Android-Tablet, die Kunden-App eine gewöhnliche Handy-App, und das gesamte System " +
        "öffnet sich zusätzlich im Browser auf jedem Laptop oder Desktop. Es gibt kein " +
        "proprietäres Terminal zu kaufen.",
    ],
    industriesTitle: "Gebaut für",
    industries: [
      ["Restaurants", "Tische, Gänge, Küchenbons, Grössen und Zusätze"],
      ["Cafés und Bäckereien", "Schnelle Wiederholbestellungen, Thekenverkauf, Schichtübergabe"],
      ["Supermärkte", "Barcode-Scan, Lieferanten, Bestellungen, Inventur"],
      ["Apotheken", "Kontrollierte Aufzeichnungen, exakter Bestand, Prüfprotokoll"],
      ["Take-away und Lieferung", "Zonen, Gebühren, Fahrer, Live-Verfolgung"],
      ["Jede Verkaufstheke", "Produkte, Preise, Belege, Auswertungen"],
    ],
    platformTitle: "Drei Zugänge, ein Datenbestand",
    platforms: [
      ["Kassenta POS", "Android-Tablet oder Android-Handy. Kasse, Lager, Personal und Berichte.", LINKS.pos],
      ["Kassenta Order", "Android-Handy. Ihre Kunden stöbern, bestellen und verfolgen.", LINKS.order],
      ["Desktop und Laptop", "Dasselbe System in jedem Browser. Nichts zu installieren.", LINKS.desktop],
    ],
  },
};

const sections = [
  { id: "web", en: { n: "01", title: "The website", sub: "kassenta.com" },
    de: { n: "01", title: "Die Website", sub: "kassenta.com" } },
  { id: "start", en: { n: "02", title: "Getting started", sub: "Activation and sign-in" },
    de: { n: "02", title: "Erste Schritte", sub: "Aktivierung und Anmeldung" } },
  { id: "sell", en: { n: "03", title: "Selling", sub: "The till" },
    de: { n: "03", title: "Verkaufen", sub: "Die Kasse" } },
  { id: "orders", en: { n: "04", title: "Orders", sub: "Online, tables and counter" },
    de: { n: "04", title: "Bestellungen", sub: "Online, Tische und Theke" } },
  { id: "catalogue", en: { n: "05", title: "Products and customers", sub: "The catalogue" },
    de: { n: "05", title: "Produkte und Kunden", sub: "Der Katalog" } },
  { id: "reports", en: { n: "06", title: "Reports", sub: "Seven views of the business" },
    de: { n: "06", title: "Berichte", sub: "Sieben Sichten auf den Betrieb" } },
  { id: "settings", en: { n: "07", title: "Settings", sub: "Seventeen management areas" },
    de: { n: "07", title: "Einstellungen", sub: "Siebzehn Verwaltungsbereiche" } },
  { id: "delivery", en: { n: "08", title: "Delivery", sub: "Zones, drivers and promotions" },
    de: { n: "08", title: "Lieferung", sub: "Zonen, Fahrer und Aktionen" } },
  { id: "customer", en: { n: "09", title: "Kassenta Order", sub: "The customer app" },
    de: { n: "09", title: "Kassenta Order", sub: "Die Kunden-App" } },
];

/**
 * One entry per screen. Written after driving each screen in the running app;
 * the feature lines describe controls that are actually present.
 */
const screens = [
  // ── 01 website ──────────────────────────────────────────────────────────
  { shot: "site-home", section: "web",
    en: { title: "kassenta.com", sub: "The public site",
      desc: "The marketing site introduces the system, the industry presets and the pricing, and links straight into the live app.",
      features: ["Features, Industries, Pricing, Compliance, About and Contact",
        "Book a live demo", "Compare all industry presets",
        "Answers on hardware, offline working, data import and multi-branch",
        "Open the POS or order online directly from the header",
        "Privacy, Terms, Imprint and account deletion in the footer"] },
    de: { title: "kassenta.com", sub: "Die öffentliche Website",
      desc: "Die Website stellt das System, die Branchenvoreinstellungen und die Preise vor und führt direkt in die laufende Anwendung.",
      features: ["Funktionen, Branchen, Preise, Compliance, Über uns und Kontakt",
        "Live-Demo buchen", "Alle Branchenvoreinstellungen vergleichen",
        "Antworten zu Hardware, Offline-Betrieb, Datenimport und Filialen",
        "Kasse öffnen oder online bestellen direkt aus der Kopfzeile",
        "Datenschutz, AGB, Impressum und Kontolöschung in der Fusszeile"] } },

  // ── 02 getting started ──────────────────────────────────────────────────
  { shot: "pos-intro", section: "start",
    en: { title: "Welcome", sub: "First launch",
      desc: "The app opens in the language the shop chooses. Three are built in and the choice can be changed at any time.",
      features: ["English, Deutsch and العربية", "Right-to-left layout for Arabic", "Get Started"] },
    de: { title: "Willkommen", sub: "Erster Start",
      desc: "Die App startet in der vom Betrieb gewählten Sprache. Drei sind eingebaut, die Wahl ist jederzeit änderbar.",
      features: ["English, Deutsch und العربية", "Rechts-nach-links-Layout für Arabisch", "Loslegen"] } },

  { shot: "pos-license-gate", section: "start",
    en: { title: "Activation", sub: "Licence key",
      desc: "A shop is activated once with the licence key issued on subscription. There is no open sign-up inside the till, which is what keeps one shop's data out of another's.",
      features: ["Licence key and store email", "Sign in with Google to start a trial store",
        "Subscribe now", "Link to kassenta.com"] },
    de: { title: "Aktivierung", sub: "Lizenzschlüssel",
      desc: "Ein Betrieb wird einmalig mit dem bei Abschluss ausgestellten Lizenzschlüssel aktiviert. In der Kasse gibt es keine offene Registrierung — genau das hält die Daten der Betriebe getrennt.",
      features: ["Lizenzschlüssel und Geschäfts-E-Mail", "Mit Google anmelden für ein Testkonto",
        "Jetzt abonnieren", "Link zu kassenta.com"] } },

  { shot: "pos-login", section: "start",
    en: { title: "Staff sign-in", sub: "PIN pad",
      desc: "After activation the till asks for a staff PIN. It is a shift lock for a shared counter device, not a second account system, and it decides what each person may see.",
      features: ["Numeric PIN per employee", "Role decides the visible screens",
        "Manager sees everything; a cashier sees the till and customers only",
        "Log out of the store licence"] },
    de: { title: "Personalanmeldung", sub: "PIN-Feld",
      desc: "Nach der Aktivierung verlangt die Kasse eine Personal-PIN. Sie ist eine Schichtsperre für ein gemeinsam genutztes Gerät, kein zweites Kontosystem, und bestimmt, was jede Person sehen darf.",
      features: ["Numerische PIN je Mitarbeitende", "Die Rolle bestimmt die sichtbaren Bildschirme",
        "Die Leitung sieht alles; eine Kassenkraft nur Kasse und Kunden",
        "Von der Geschäftslizenz abmelden"] } },

  { shot: "pos-onboarding", section: "start",
    en: { title: "Store type", sub: "Industry preset",
      desc: "The shop picks what it is, and the app arranges itself accordingly. The choice sets the default categories, the receipt layout and which screens appear first.",
      features: ["Restaurant", "Supermarket", "Pharmacy", "Others", "Changeable later in Settings"] },
    de: { title: "Geschäftsart", sub: "Branchenvoreinstellung",
      desc: "Der Betrieb wählt, was er ist, und die App richtet sich danach aus. Die Wahl bestimmt die Standardkategorien, das Beleglayout und welche Bildschirme zuerst erscheinen.",
      features: ["Restaurant", "Supermarkt", "Apotheke", "Sonstige", "Später in den Einstellungen änderbar"] } },

  // ── 03 selling ──────────────────────────────────────────────────────────
  { shot: "pos-sell", section: "sell",
    en: { title: "The till", sub: "Selling screen",
      desc: "The main working screen. Products on the left, the running ticket on the right, and everything a busy counter needs within one tap.",
      features: ["Search and barcode scanner", "Category filter across the catalogue",
        "Customer lookup by phone number", "Live clock and date",
        "Calls, Refresh, Dark mode, Zero Out Shift and Invoices in the header",
        "Subtotal, tax, manual adjustment and total", "Notes on the ticket"] },
    de: { title: "Die Kasse", sub: "Verkaufsbildschirm",
      desc: "Der Hauptarbeitsbildschirm. Produkte links, der laufende Bon rechts, und alles, was eine belebte Theke braucht, mit einem Fingertipp.",
      features: ["Suche und Barcode-Scanner", "Kategoriefilter über den Katalog",
        "Kundensuche über die Telefonnummer", "Live-Uhr und Datum",
        "Anrufe, Aktualisieren, Dunkelmodus, Schicht abrechnen und Rechnungen in der Kopfzeile",
        "Zwischensumme, Steuer, manuelle Anpassung und Gesamtsumme", "Notizen auf dem Bon"] } },

  { shot: "pos-sell-cart", section: "sell",
    en: { title: "A ticket in progress", sub: "The cart",
      desc: "Items drop into the ticket as they are tapped. Quantities, removals and per-line editing all happen without leaving the screen.",
      features: ["Line quantity up and down", "Remove a line", "Per-line price shown",
        "Walk-in customer or a named account", "Item count and total on the checkout button"] },
    de: { title: "Ein laufender Bon", sub: "Der Warenkorb",
      desc: "Artikel landen beim Antippen im Bon. Mengen, Entfernen und zeilenweises Bearbeiten geschehen, ohne den Bildschirm zu verlassen.",
      features: ["Zeilenmenge erhöhen und verringern", "Zeile entfernen", "Zeilenpreis sichtbar",
        "Laufkundschaft oder ein benanntes Konto", "Artikelzahl und Summe auf der Kassieren-Schaltfläche"] } },

  { shot: "pos-hdr-calls", section: "sell",
    en: { title: "Calls", sub: "Caller ID",
      desc: "Incoming calls are matched against the customer list, so an order can be started from a ringing phone without asking for a name and address again.",
      features: ["Incoming number matched to a customer", "Order history for that caller",
        "Start an order from the call"] },
    de: { title: "Anrufe", sub: "Rufnummernerkennung",
      desc: "Eingehende Anrufe werden mit der Kundenliste abgeglichen, sodass eine Bestellung direkt aus dem klingelnden Telefon beginnen kann, ohne erneut nach Name und Adresse zu fragen.",
      features: ["Eingehende Nummer einer Kundschaft zugeordnet", "Bestellhistorie zu diesem Anruf",
        "Bestellung aus dem Anruf starten"] } },

  { shot: "pos-hdr-invoices", section: "sell",
    en: { title: "Invoices", sub: "Past receipts",
      desc: "Every receipt the till has issued, reachable from the selling screen so a reprint never means leaving the counter.",
      features: ["Receipt history", "Reprint", "Search a past sale"] },
    de: { title: "Rechnungen", sub: "Frühere Belege",
      desc: "Jeder von der Kasse ausgestellte Beleg, direkt vom Verkaufsbildschirm erreichbar, sodass ein Nachdruck nie bedeutet, die Theke zu verlassen.",
      features: ["Belegverlauf", "Nachdruck", "Einen früheren Verkauf suchen"] } },

  { shot: "pos-hdr-shift", section: "sell",
    en: { title: "Zero out shift", sub: "Closing up",
      desc: "Ends the shift and settles the drawer against what the till says should be in it.",
      features: ["Shift takings totalled", "Counted against expected",
        "Closes the cash drawer session"] },
    de: { title: "Schicht abrechnen", sub: "Abschluss",
      desc: "Beendet die Schicht und gleicht die Kassenlade mit dem ab, was laut Kasse darin sein sollte.",
      features: ["Schichteinnahmen summiert", "Gezählt gegen Soll",
        "Schliesst die Kassenladen-Sitzung"] } },

  { shot: "pos-customer-picker", section: "sell",
    en: { title: "Choosing a customer", sub: "Walk-in or named",
      desc: "A sale can stay anonymous or be attached to a customer, which is what makes delivery, loyalty and order history possible.",
      features: ["Search the customer list", "Walk-in customer by default",
        "Create a customer from the till", "Address carried into delivery"] },
    de: { title: "Kundschaft wählen", sub: "Laufkundschaft oder benannt",
      desc: "Ein Verkauf kann anonym bleiben oder einer Kundschaft zugeordnet werden — Voraussetzung für Lieferung, Treueprogramm und Bestellhistorie.",
      features: ["Kundenliste durchsuchen", "Standardmässig Laufkundschaft",
        "Kundschaft an der Kasse anlegen", "Adresse wird in die Lieferung übernommen"] } },

  { shot: "pos-notes", section: "sell",
    en: { title: "Notes", sub: "Anything the kitchen needs to know",
      desc: "A free note on the ticket for the things no menu covers: allergies, a doorbell that does not work, a table that wants everything at once.",
      features: ["Free text on the ticket", "Travels to the kitchen", "Kept with the order record"] },
    de: { title: "Notizen", sub: "Was die Küche wissen muss",
      desc: "Eine freie Notiz auf dem Bon für alles, was keine Karte abdeckt: Allergien, eine defekte Klingel, ein Tisch, der alles gleichzeitig möchte.",
      features: ["Freitext auf dem Bon", "Geht an die Küche", "Bleibt beim Bestelldatensatz"] } },

  { shot: "pos-extras", section: "sell",
    en: { title: "Sizes and extras", sub: "Modifiers",
      desc: "A product with variants opens its own sheet. Sizes carry their own prices, extras are grouped and colour-coded by kind, and sauces that cost nothing are marked free.",
      features: ["Size with its own price, for example 33cm and 45cm",
        "Extras grouped as vegetables, meat, fish and cheese",
        "Per-extra surcharge shown on the tile", "Cheese crust priced by size",
        "Free sauces", "Back to sizes without losing the selection"] },
    de: { title: "Grössen und Extras", sub: "Zusätze",
      desc: "Ein Produkt mit Varianten öffnet ein eigenes Blatt. Grössen tragen eigene Preise, Extras sind nach Art gruppiert und farblich unterschieden, kostenlose Saucen sind als gratis gekennzeichnet.",
      features: ["Grösse mit eigenem Preis, etwa 33 cm und 45 cm",
        "Extras gruppiert nach Gemüse, Fleisch, Fisch und Käse",
        "Aufpreis je Extra auf der Kachel sichtbar", "Käserand nach Grösse bepreist",
        "Gratis-Saucen", "Zurück zu den Grössen ohne Verlust der Auswahl"] } },

  { shot: "pos-checkout", section: "sell",
    en: { title: "Taking payment", sub: "Complete payment",
      desc: "One sheet closes the sale. The order is itemised, the payment method is chosen, and a delivery can be handed to a driver in the same step.",
      features: ["Cash, Card, TWINT and NFC Pay", "Cash received, with change worked out",
        "Itemised order summary", "Assign a delivery vehicle and driver",
        "Delivery fee adjustable up or down"] },
    de: { title: "Zahlung annehmen", sub: "Zahlung abschliessen",
      desc: "Ein Blatt schliesst den Verkauf ab. Die Bestellung ist aufgeschlüsselt, die Zahlungsart wird gewählt, und eine Lieferung kann im selben Schritt einem Fahrer übergeben werden.",
      features: ["Bar, Karte, TWINT und NFC Pay", "Erhaltener Betrag mit Rückgeldberechnung",
        "Aufgeschlüsselte Bestellübersicht", "Lieferfahrzeug und Fahrer zuweisen",
        "Liefergebühr nach oben oder unten anpassbar"] } },

  // ── 04 orders ───────────────────────────────────────────────────────────
  { shot: "ord-all", section: "orders",
    en: { title: "All orders", sub: "One queue",
      desc: "Every order the shop has taken, whatever the channel, in one list with a live status on each.",
      features: ["Active, Done and All filters", "Share a tracking link with the customer",
        "Chat with the customer", "Move an order through Preparing and onwards"] },
    de: { title: "Alle Bestellungen", sub: "Eine Warteschlange",
      desc: "Jede Bestellung des Betriebs, gleich über welchen Kanal, in einer Liste mit Live-Status.",
      features: ["Filter Aktiv, Erledigt und Alle", "Verfolgungslink mit der Kundschaft teilen",
        "Chat mit der Kundschaft", "Bestellung durch In Zubereitung und weiter bewegen"] } },

  { shot: "ord-online", section: "orders",
    en: { title: "Online orders", sub: "From the customer app",
      desc: "Orders placed in Kassenta Order or on the web shop arrive here, already itemised and paid or marked for cash on delivery.",
      features: ["Separated from counter sales", "Customer details attached",
        "Accept and move to the kitchen", "Tracking link per order"] },
    de: { title: "Onlinebestellungen", sub: "Aus der Kunden-App",
      desc: "Bestellungen aus Kassenta Order oder dem Webshop kommen hier an, bereits aufgeschlüsselt und bezahlt oder als Barzahlung bei Lieferung gekennzeichnet.",
      features: ["Getrennt vom Thekenverkauf", "Kundendaten angehängt",
        "Annehmen und in die Küche geben", "Verfolgungslink je Bestellung"] } },

  { shot: "ord-tables", section: "orders",
    en: { title: "Table orders", sub: "Dine-in",
      desc: "Orders opened against a table, so a bill can stay open while guests keep ordering.",
      features: ["Order tied to a table number", "Add to an open bill",
        "Close and pay from the same screen"] },
    de: { title: "Tischbestellungen", sub: "Im Haus",
      desc: "Bestellungen auf einen Tisch, sodass eine Rechnung offen bleibt, während die Gäste weiter bestellen.",
      features: ["Bestellung an eine Tischnummer gebunden", "Zu einer offenen Rechnung hinzufügen",
        "Vom selben Bildschirm abschliessen und kassieren"] } },

  { shot: "ord-pos", section: "orders",
    en: { title: "Counter sales", sub: "Taken at the till",
      desc: "Sales rung up directly on the till, kept apart from online and table orders so each channel can be read on its own.",
      features: ["Filtered to till sales", "Same status flow as every other channel",
        "Reprint or review any receipt"] },
    de: { title: "Thekenverkäufe", sub: "An der Kasse erfasst",
      desc: "Direkt an der Kasse gebuchte Verkäufe, getrennt von Online- und Tischbestellungen, damit jeder Kanal für sich lesbar bleibt.",
      features: ["Auf Kassenverkäufe gefiltert", "Gleicher Statusablauf wie bei jedem Kanal",
        "Jeden Beleg erneut drucken oder ansehen"] } },

  { shot: "pos-table-qr", section: "orders",
    en: { title: "Table QR codes", sub: "Order from the table",
      desc: "A code per table. A guest scans it, the menu opens on their own phone, and the order lands against that table in the till.",
      features: ["Generate a code for one table or all at once",
        "Generate All across every table in the room", "Preview before printing",
        "Print one or print all"] },
    de: { title: "Tisch-QR-Codes", sub: "Vom Tisch aus bestellen",
      desc: "Ein Code je Tisch. Ein Gast scannt ihn, die Karte öffnet sich auf dem eigenen Handy, und die Bestellung landet in der Kasse auf diesem Tisch.",
      features: ["Code für einen Tisch oder alle auf einmal erzeugen",
        "Alle erzeugen für jeden Tisch im Raum", "Vorschau vor dem Druck",
        "Einzeln oder alle drucken"] } },

  // ── 05 catalogue ────────────────────────────────────────────────────────
  { shot: "pos-products", section: "catalogue",
    en: { title: "Products", sub: "Catalogue and stock",
      desc: "The full catalogue with its article numbers, categories, prices and stock on hand.",
      features: ["Article number per product", "Category per product", "Price and stock level",
        "Search across the catalogue", "Filter by category", "Add, edit and archive"] },
    de: { title: "Produkte", sub: "Katalog und Bestand",
      desc: "Der vollständige Katalog mit Artikelnummern, Kategorien, Preisen und verfügbarem Bestand.",
      features: ["Artikelnummer je Produkt", "Kategorie je Produkt", "Preis und Lagerbestand",
        "Suche über den Katalog", "Nach Kategorie filtern", "Anlegen, bearbeiten und archivieren"] } },

  { shot: "pos-product-edit", section: "catalogue",
    en: { title: "Editing a product", sub: "The product sheet",
      desc: "Everything about one article in a single sheet: what it costs, what it is called, where it sits and how much is left.",
      features: ["Name, description and image", "Price and cost", "Category and article number",
        "Stock level", "Sizes and extras", "Save or archive"] },
    de: { title: "Ein Produkt bearbeiten", sub: "Das Produktblatt",
      desc: "Alles zu einem Artikel auf einem Blatt: Preis, Bezeichnung, Einordnung und Restbestand.",
      features: ["Name, Beschreibung und Bild", "Verkaufs- und Einkaufspreis", "Kategorie und Artikelnummer",
        "Lagerbestand", "Grössen und Extras", "Speichern oder archivieren"] } },

  { shot: "pos-employee-edit", section: "catalogue",
    en: { title: "Editing an employee", sub: "The staff sheet",
      desc: "One person's record: how to reach them, what they may do, and the PIN that lets them onto the till.",
      features: ["Name, email and phone", "Role and permissions", "PIN",
        "Hourly rate and commission", "Branch", "Active or inactive"] },
    de: { title: "Mitarbeitende bearbeiten", sub: "Das Personalblatt",
      desc: "Der Datensatz einer Person: Erreichbarkeit, Berechtigungen und die PIN für den Zugang zur Kasse.",
      features: ["Name, E-Mail und Telefon", "Rolle und Rechte", "PIN",
        "Stundensatz und Provision", "Filiale", "Aktiv oder inaktiv"] } },

  { shot: "pos-customers", section: "catalogue",
    en: { title: "Customers", sub: "The address book",
      desc: "Every customer the shop has served, whether they gave a name or ordered as a guest. This demo store holds more than forty thousand.",
      features: ["Total count always visible", "Search by name or phone",
        "Guests kept without personal details", "Import a customer list",
        "Add a customer by hand"] },
    de: { title: "Kunden", sub: "Das Adressbuch",
      desc: "Jede bediente Kundschaft, ob mit Namen oder als Gast bestellt. Dieser Demobetrieb führt über vierzigtausend Einträge.",
      features: ["Gesamtzahl stets sichtbar", "Suche nach Name oder Telefon",
        "Gäste ohne persönliche Daten geführt", "Kundenliste importieren",
        "Kundschaft von Hand anlegen"] } },
  // ── 06 reports ──────────────────────────────────────────────────────────
  { shot: "rep-overview", section: "reports",
    en: { title: "Overview", sub: "The business at a glance",
      desc: "The opening report. Takings, orders and the direction of travel, with every other report one tap away.",
      features: ["Seven report views in one place", "Sales CSV, Inventory CSV, Profit CSV and Performance CSV",
        "Generate more insights", "View all"] },
    de: { title: "Übersicht", sub: "Der Betrieb auf einen Blick",
      desc: "Der Einstiegsbericht. Umsatz, Bestellungen und die Entwicklung, mit jedem weiteren Bericht einen Fingertipp entfernt.",
      features: ["Sieben Berichtssichten an einem Ort", "Verkäufe, Bestand, Gewinn und Leistung als CSV",
        "Weitere Auswertungen erzeugen", "Alle anzeigen"] } },

  { shot: "pos-reports-dark", section: "reports",
    en: { title: "Dark mode", sub: "The same reports at night",
      desc: "The whole system has a dark theme, switched from the till header. On a screen that faces a dining room after dark it is the difference between a working tool and a lamp.",
      features: ["Switched from the till header", "Applies across every screen",
        "Remembered per device", "Light or dark set in Appearance"] },
    de: { title: "Dunkelmodus", sub: "Dieselben Berichte bei Nacht",
      desc: "Das gesamte System hat ein dunkles Thema, umschaltbar in der Kopfzeile der Kasse. Auf einem Bildschirm, der abends in den Gastraum zeigt, ist das der Unterschied zwischen Werkzeug und Lampe.",
      features: ["Umschaltbar in der Kopfzeile", "Gilt für jeden Bildschirm",
        "Je Gerät gemerkt", "Hell oder dunkel unter Darstellung"] } },

  { shot: "rep-sales", section: "reports",
    en: { title: "Sales", sub: "What sold",
      desc: "Takings broken down over time and by product, so the shop can see what actually earns its place on the menu.",
      features: ["Revenue over a chosen period", "Best and worst sellers",
        "Export to CSV for a bookkeeper"] },
    de: { title: "Verkäufe", sub: "Was verkauft wurde",
      desc: "Umsätze nach Zeitraum und Produkt aufgeschlüsselt, damit erkennbar wird, was seinen Platz auf der Karte wirklich verdient.",
      features: ["Umsatz über einen gewählten Zeitraum", "Beste und schwächste Verkäufer",
        "CSV-Export für die Buchhaltung"] } },

  { shot: "rep-inventory", section: "reports",
    en: { title: "Inventory", sub: "What is left",
      desc: "Stock on hand against what has moved, so reordering is a decision rather than a guess.",
      features: ["Stock level per article", "Movement over the period",
        "Low-stock visibility", "Inventory CSV"] },
    de: { title: "Bestand", sub: "Was übrig ist",
      desc: "Verfügbarer Bestand gegen den Abgang, damit Nachbestellen eine Entscheidung ist und keine Vermutung.",
      features: ["Bestand je Artikel", "Bewegung im Zeitraum",
        "Sichtbarkeit knapper Bestände", "Bestand als CSV"] } },

  { shot: "rep-returns", section: "reports",
    en: { title: "Returns", sub: "What came back",
      desc: "Refunds and returned goods kept as their own record rather than folded into sales.",
      features: ["Returns over the period", "Reason held against each",
        "Reconciles with the Returns and Refunds area in Settings"] },
    de: { title: "Retouren", sub: "Was zurückkam",
      desc: "Rückerstattungen und Rückgaben als eigener Nachweis geführt, nicht in die Verkäufe eingerechnet.",
      features: ["Retouren im Zeitraum", "Grund je Vorgang hinterlegt",
        "Stimmt mit dem Bereich Retouren und Rückerstattungen überein"] } },

  { shot: "rep-finance", section: "reports",
    en: { title: "Finance", sub: "Money in and out",
      desc: "Revenue set against expenses, so the number that matters is the one the shop keeps.",
      features: ["Revenue against recorded expenses", "Profit worked out over the period",
        "Profit CSV"] },
    de: { title: "Finanzen", sub: "Geld ein und aus",
      desc: "Umsatz gegen Ausgaben gestellt, damit die entscheidende Zahl die ist, die im Betrieb bleibt.",
      features: ["Umsatz gegen erfasste Ausgaben", "Gewinn über den Zeitraum berechnet",
        "Gewinn als CSV"] } },

  { shot: "rep-activity", section: "reports",
    en: { title: "Activity", sub: "Who did what",
      desc: "A record of actions taken in the system, tied to the member of staff who took them.",
      features: ["Action, time and employee", "Covers price changes, refunds and voids",
        "Backs the Activity Log in Settings"] },
    de: { title: "Aktivität", sub: "Wer was getan hat",
      desc: "Ein Nachweis der im System ausgeführten Vorgänge, verknüpft mit der ausführenden Person.",
      features: ["Vorgang, Zeit und Mitarbeitende", "Umfasst Preisänderungen, Erstattungen und Stornos",
        "Grundlage des Aktivitätsprotokolls in den Einstellungen"] } },

  { shot: "rep-delivery", section: "reports",
    en: { title: "Delivery", sub: "The fleet",
      desc: "Delivery performance on its own terms: how many went out, how far, and how long they took.",
      features: ["Deliveries over the period", "Performance per driver",
        "Performance CSV"] },
    de: { title: "Lieferung", sub: "Die Flotte",
      desc: "Lieferleistung eigenständig betrachtet: wie viele hinausgingen, wie weit und wie lange sie brauchten.",
      features: ["Lieferungen im Zeitraum", "Leistung je Fahrer",
        "Leistung als CSV"] } },

  // ── 07 settings ─────────────────────────────────────────────────────────
  { shot: "pos-settings", section: "settings",
    en: { title: "Settings", sub: "Seventeen areas",
      desc: "Everything that runs the shop rather than the sale. Each row carries its own live count, so the state of the business is readable before opening anything.",
      features: ["Employees, Branches and Store Settings", "Payment Gateways and Bulk Import",
        "QR Tables, Suppliers and Expenses", "Attendance, Shift Monitor and Purchase Orders",
        "Activity Log, Returns and Refunds, Cash Drawer"] },
    de: { title: "Einstellungen", sub: "Siebzehn Bereiche",
      desc: "Alles, was den Betrieb steuert statt den Verkauf. Jede Zeile trägt ihren eigenen Live-Zähler, sodass der Zustand des Betriebs lesbar ist, bevor man etwas öffnet.",
      features: ["Mitarbeitende, Filialen und Geschäftseinstellungen", "Zahlungsanbieter und Massenimport",
        "QR-Tische, Lieferanten und Ausgaben", "Anwesenheit, Schichtmonitor und Bestellungen",
        "Aktivitätsprotokoll, Retouren und Rückerstattungen, Kassenlade"] } },

  { shot: "set-employees", section: "settings",
    en: { title: "Employees", sub: "Staff and permissions",
      desc: "Who works here, what they may do, and the PIN each uses at the till.",
      features: ["Role per employee", "Permissions attached to the role",
        "PIN per employee", "Hourly rate and commission", "Activate and deactivate"] },
    de: { title: "Mitarbeitende", sub: "Personal und Rechte",
      desc: "Wer hier arbeitet, was er darf, und die PIN, die jede Person an der Kasse benutzt.",
      features: ["Rolle je Mitarbeitende", "Rechte an die Rolle gebunden",
        "PIN je Mitarbeitende", "Stundensatz und Provision", "Aktivieren und deaktivieren"] } },

  { shot: "set-branches", section: "settings",
    en: { title: "Branches", sub: "More than one location",
      desc: "A shop with several locations runs them from one account, with stock and staff attached to the branch they belong to.",
      features: ["Location list", "Staff assigned per branch",
        "Stock held per branch", "Reports readable per branch or combined"] },
    de: { title: "Filialen", sub: "Mehr als ein Standort",
      desc: "Ein Betrieb mit mehreren Standorten führt sie über ein Konto, mit Bestand und Personal an der jeweiligen Filiale.",
      features: ["Standortliste", "Personal je Filiale zugeordnet",
        "Bestand je Filiale geführt", "Berichte je Filiale oder zusammengefasst"] } },

  { shot: "set-store", section: "settings",
    en: { title: "Store settings", sub: "Details on the receipt",
      desc: "The shop's own details, as they appear on every printed and emailed receipt.",
      features: ["Name, address and contact", "Tax details", "Receipt layout",
        "Currency and language"] },
    de: { title: "Geschäftseinstellungen", sub: "Angaben auf dem Beleg",
      desc: "Die Angaben des Betriebs, wie sie auf jedem gedruckten und versandten Beleg erscheinen.",
      features: ["Name, Adresse und Kontakt", "Steuerangaben", "Beleglayout",
        "Währung und Sprache"] } },

  { shot: "set-payments", section: "settings",
    en: { title: "Payment gateways", sub: "How money arrives",
      desc: "Card payment is connected through Stripe, with a test mode so a shop can rehearse the whole flow before taking a real card.",
      features: ["Stripe connection with connected or disconnected state",
        "Test mode", "Currency", "Auto capture",
        "Enabled payment methods", "Test connection",
        "Cash always available with nothing configured"] },
    de: { title: "Zahlungsanbieter", sub: "Wie das Geld ankommt",
      desc: "Die Kartenzahlung wird über Stripe angebunden, mit einem Testmodus, damit ein Betrieb den gesamten Ablauf proben kann, bevor eine echte Karte belastet wird.",
      features: ["Stripe-Verbindung mit Status verbunden oder getrennt",
        "Testmodus", "Währung", "Automatischer Einzug",
        "Aktivierte Zahlungsarten", "Verbindung testen",
        "Bar stets ohne Einrichtung verfügbar"] } },

  { shot: "set-import", section: "settings",
    en: { title: "Bulk import", sub: "Bringing data in",
      desc: "An existing product list or customer file can be loaded rather than retyped, which is usually the difference between switching and not switching.",
      features: ["Import products", "Import customers", "Spreadsheet upload",
        "Existing records matched rather than duplicated"] },
    de: { title: "Massenimport", sub: "Daten übernehmen",
      desc: "Eine vorhandene Produktliste oder Kundendatei lässt sich laden statt abtippen — meist der Unterschied zwischen Wechseln und Nichtwechseln.",
      features: ["Produkte importieren", "Kunden importieren", "Tabellen-Upload",
        "Vorhandene Einträge abgeglichen statt doppelt angelegt"] } },

  { shot: "set-qr-tables", section: "settings",
    en: { title: "QR tables", sub: "The room",
      desc: "The tables themselves: how many, what they are called, and the code that belongs to each.",
      features: ["Table list", "Code per table", "Add and rename tables",
        "Feeds the Table QR screen"] },
    de: { title: "QR-Tische", sub: "Der Raum",
      desc: "Die Tische selbst: wie viele, wie sie heissen, und welcher Code zu welchem gehört.",
      features: ["Tischliste", "Code je Tisch", "Tische anlegen und umbenennen",
        "Speist den Tisch-QR-Bildschirm"] } },

  { shot: "set-suppliers", section: "settings",
    en: { title: "Suppliers", sub: "Where stock comes from",
      desc: "The businesses the shop buys from, held against the goods they supply.",
      features: ["Supplier list with contact details", "Goods linked to a supplier",
        "Feeds purchase orders"] },
    de: { title: "Lieferanten", sub: "Woher die Ware kommt",
      desc: "Die Betriebe, bei denen eingekauft wird, verknüpft mit den gelieferten Waren.",
      features: ["Lieferantenliste mit Kontaktdaten", "Waren einem Lieferanten zugeordnet",
        "Speist die Bestellungen"] } },

  { shot: "set-expenses", section: "settings",
    en: { title: "Expenses", sub: "Money going out",
      desc: "Costs recorded as they happen, so the finance report shows profit rather than just takings.",
      features: ["Expense with amount and date", "Category per expense",
        "Feeds the Finance report"] },
    de: { title: "Ausgaben", sub: "Geld, das hinausgeht",
      desc: "Kosten werden erfasst, sobald sie anfallen, damit der Finanzbericht Gewinn zeigt und nicht nur Umsatz.",
      features: ["Ausgabe mit Betrag und Datum", "Kategorie je Ausgabe",
        "Speist den Finanzbericht"] } },

  { shot: "set-attendance", section: "settings",
    en: { title: "Attendance", sub: "Hours worked",
      desc: "When staff clocked in and out, kept as the record behind wages.",
      features: ["Clock-in and clock-out per employee", "Hours totalled per period",
        "Works with the hourly rate on the employee record"] },
    de: { title: "Anwesenheit", sub: "Geleistete Stunden",
      desc: "Wann das Personal ein- und ausgestempelt hat, als Nachweis hinter dem Lohn.",
      features: ["Kommen und Gehen je Mitarbeitende", "Stunden je Zeitraum summiert",
        "Arbeitet mit dem Stundensatz im Personalsatz"] } },

  { shot: "set-shifts", section: "settings",
    en: { title: "Shift monitor", sub: "Who is on now",
      desc: "The shifts currently open, and what has been taken during each.",
      features: ["Active shifts listed live", "Takings per shift",
        "Pairs with Zero Out Shift on the till"] },
    de: { title: "Schichtmonitor", sub: "Wer gerade arbeitet",
      desc: "Die derzeit offenen Schichten und was in jeder eingenommen wurde.",
      features: ["Aktive Schichten live aufgelistet", "Einnahmen je Schicht",
        "Passt zu Schicht abrechnen an der Kasse"] } },

  { shot: "set-purchase-orders", section: "settings",
    en: { title: "Purchase orders", sub: "Restocking",
      desc: "Orders placed with suppliers, tracked from raised to received so stock updates itself on arrival.",
      features: ["Order raised against a supplier", "Lines with quantities",
        "Received goods added to stock"] },
    de: { title: "Bestellungen", sub: "Nachschub",
      desc: "Bei Lieferanten aufgegebene Bestellungen, verfolgt von der Aufgabe bis zum Eingang, sodass sich der Bestand beim Eintreffen selbst aktualisiert.",
      features: ["Bestellung an einen Lieferanten", "Positionen mit Mengen",
        "Eingegangene Ware wird dem Bestand zugebucht"] } },

  { shot: "set-activity", section: "settings",
    en: { title: "Activity log", sub: "The audit trail",
      desc: "A running record of what was done in the system and by whom. It is the answer to the question a shop asks after something goes wrong.",
      features: ["Entry per action with time and employee",
        "Covers price edits, refunds, voids and settings changes",
        "Read-only"] },
    de: { title: "Aktivitätsprotokoll", sub: "Das Prüfprotokoll",
      desc: "Ein fortlaufender Nachweis, was im System getan wurde und von wem. Es ist die Antwort auf die Frage, die ein Betrieb stellt, wenn etwas schiefging.",
      features: ["Eintrag je Vorgang mit Zeit und Mitarbeitenden",
        "Umfasst Preisänderungen, Erstattungen, Stornos und Einstellungen",
        "Nur lesbar"] } },

  { shot: "set-returns", section: "settings",
    en: { title: "Returns and refunds", sub: "Undoing a sale",
      desc: "Returns handled as their own transaction, so stock, takings and the audit trail all stay consistent.",
      features: ["Return against an original sale", "Reason recorded",
        "Stock returned to the shelf", "Feeds the Returns report"] },
    de: { title: "Retouren und Rückerstattungen", sub: "Einen Verkauf rückgängig machen",
      desc: "Rückgaben als eigener Vorgang, sodass Bestand, Einnahmen und Prüfprotokoll stimmig bleiben.",
      features: ["Retoure zu einem Originalverkauf", "Grund erfasst",
        "Ware zurück in den Bestand", "Speist den Retourenbericht"] } },

  { shot: "set-cash-drawer", section: "settings",
    en: { title: "Cash drawer", sub: "Movements in and out",
      desc: "Every movement of cash is recorded against an open shift, with a reason attached. Without an open shift the drawer refuses the operation rather than recording it against nobody.",
      features: ["Withdrawal, Deposit or Count", "Amount, required",
        "Reason for the operation", "Record operation",
        "Refuses to act when no shift is open"] },
    de: { title: "Kassenlade", sub: "Bewegungen ein und aus",
      desc: "Jede Barbewegung wird einer offenen Schicht mit Begründung zugeordnet. Ohne offene Schicht verweigert die Lade den Vorgang, statt ihn niemandem zuzuschreiben.",
      features: ["Entnahme, Einlage oder Zählung", "Betrag, erforderlich",
        "Grund des Vorgangs", "Vorgang erfassen",
        "Verweigert den Vorgang, wenn keine Schicht offen ist"] } },

  { shot: "set-warehouses", section: "settings",
    en: { title: "Warehouses", sub: "Where stock sits",
      desc: "Stock can be held in more than one place, with one marked as the default so a sale always knows where to draw from.",
      features: ["Warehouse per branch", "Address per warehouse",
        "One marked default"] },
    de: { title: "Lager", sub: "Wo die Ware liegt",
      desc: "Bestand kann an mehreren Orten liegen, einer davon als Standard markiert, damit ein Verkauf immer weiss, woher er bucht.",
      features: ["Lager je Filiale", "Adresse je Lager",
        "Eines als Standard markiert"] } },

  { shot: "set-batches", section: "settings",
    en: { title: "Product batches", sub: "Lots and expiry",
      desc: "Goods that arrive in batches can be tracked as batches, which is what a pharmacy or a grocer needs when a recall or an expiry date matters.",
      features: ["Batch per delivery", "Tracked against the product",
        "Supports expiry and recall"] },
    de: { title: "Produktchargen", sub: "Chargen und Haltbarkeit",
      desc: "Ware, die in Chargen eintrifft, lässt sich als Charge verfolgen — genau das, was eine Apotheke oder ein Lebensmittelhändler bei Rückruf oder Ablaufdatum braucht.",
      features: ["Charge je Lieferung", "Am Produkt geführt",
        "Unterstützt Haltbarkeit und Rückruf"] } },

  { shot: "set-vehicles", section: "settings",
    en: { title: "Vehicles", sub: "The fleet register",
      desc: "The vehicles that make deliveries, each with its plate, its description and the driver who takes it out.",
      features: ["Add a vehicle", "Licence plate", "Make, model and colour",
        "Driver name and phone against each"] },
    de: { title: "Fahrzeuge", sub: "Das Flottenregister",
      desc: "Die Fahrzeuge, die ausliefern, jedes mit Kennzeichen, Beschreibung und der Person, die damit unterwegs ist.",
      features: ["Fahrzeug hinzufügen", "Kennzeichen", "Marke, Modell und Farbe",
        "Fahrername und Telefon je Fahrzeug"] } },

  // ── 08 delivery ─────────────────────────────────────────────────────────
  { shot: "pos-delivery-zones", section: "delivery",
    en: { title: "Delivery zones", sub: "How far you go",
      desc: "The area the shop delivers to, drawn as zones so each can carry its own fee and minimum order.",
      features: ["Create a zone", "Fee per zone", "Minimum order per zone",
        "Orders outside every zone are refused before they are taken"] },
    de: { title: "Lieferzonen", sub: "Wie weit Sie liefern",
      desc: "Das Liefergebiet, als Zonen angelegt, sodass jede eigene Gebühr und Mindestbestellung tragen kann.",
      features: ["Zone anlegen", "Gebühr je Zone", "Mindestbestellwert je Zone",
        "Bestellungen ausserhalb jeder Zone werden vor Annahme abgelehnt"] } },

  { shot: "form-zone", section: "delivery",
    en: { title: "Creating a zone", sub: "The form",
      desc: "A zone is defined once and then applies to every online order automatically.",
      features: ["Zone name", "Delivery fee", "Minimum order value",
        "Area covered", "Active or inactive"] },
    de: { title: "Eine Zone anlegen", sub: "Das Formular",
      desc: "Eine Zone wird einmal festgelegt und gilt danach automatisch für jede Onlinebestellung.",
      features: ["Zonenname", "Liefergebühr", "Mindestbestellwert",
        "Abgedecktes Gebiet", "Aktiv oder inaktiv"] } },

  { shot: "pos-drivers", section: "delivery",
    en: { title: "Drivers", sub: "The fleet",
      desc: "The people and vehicles that carry orders out, ready to be attached to a sale at the moment of payment.",
      features: ["Driver with name and phone", "Vehicle with licence plate, make, model and colour",
        "Notes per vehicle", "Selectable on the payment sheet"] },
    de: { title: "Fahrer", sub: "Die Flotte",
      desc: "Die Personen und Fahrzeuge, die Bestellungen ausliefern, bereit zur Zuordnung im Moment der Zahlung.",
      features: ["Fahrer mit Name und Telefon", "Fahrzeug mit Kennzeichen, Marke, Modell und Farbe",
        "Notizen je Fahrzeug", "Auf dem Zahlungsblatt auswählbar"] } },

  { shot: "pos-drivers-stats", section: "delivery",
    en: { title: "Driver statistics", sub: "How the fleet performs",
      desc: "Each driver's deliveries counted and timed, so routes and rosters can be argued from numbers.",
      features: ["Deliveries per driver", "Time taken", "Compared across the fleet"] },
    de: { title: "Fahrerstatistik", sub: "Wie die Flotte arbeitet",
      desc: "Lieferungen je Fahrer gezählt und gemessen, damit Routen und Dienstpläne mit Zahlen begründbar sind.",
      features: ["Lieferungen je Fahrer", "Benötigte Zeit", "Vergleich über die Flotte"] } },

  { shot: "pos-promo-codes", section: "delivery",
    en: { title: "Promo codes", sub: "Discounts",
      desc: "Codes a customer types at checkout, each with its own rules about who may use it and how often.",
      features: ["Create a code", "Percentage or fixed discount",
        "Validity period", "Usage limit"] },
    de: { title: "Aktionscodes", sub: "Rabatte",
      desc: "Codes, die die Kundschaft beim Bezahlen eingibt, jeder mit eigenen Regeln, wer ihn wie oft nutzen darf.",
      features: ["Code anlegen", "Prozentualer oder fester Rabatt",
        "Gültigkeitszeitraum", "Nutzungsgrenze"] } },

  { shot: "form-promo", section: "delivery",
    en: { title: "Creating a promo code", sub: "The form",
      desc: "The rules that decide when a discount applies, set once when the code is made.",
      features: ["Code text the customer types", "Discount type and amount",
        "Start and end date", "Maximum uses", "Minimum order value"] },
    de: { title: "Einen Aktionscode anlegen", sub: "Das Formular",
      desc: "Die Regeln, die bestimmen, wann ein Rabatt greift — einmalig beim Anlegen des Codes festgelegt.",
      features: ["Codetext für die Kundschaft", "Rabattart und Höhe",
        "Start- und Enddatum", "Maximale Nutzungen", "Mindestbestellwert"] } },

  // ── 09 customer app ─────────────────────────────────────────────────────
  { shot: "cust-signin", section: "customer", portrait: true,
    en: { title: "Signing in", sub: "Or not signing in at all",
      desc: "A customer can create an account, use Google, or order as a guest without one. Refusing to sign up is not made into a barrier.",
      features: ["Sign in with email", "Continue with Google",
        "Create account", "Continue as guest",
        "A shortcut for shop owners into the POS"] },
    de: { title: "Anmelden", sub: "Oder eben nicht",
      desc: "Die Kundschaft kann ein Konto anlegen, Google nutzen oder ganz ohne Konto als Gast bestellen. Keine Registrierung zu wollen, wird nicht zur Hürde gemacht.",
      features: ["Mit E-Mail anmelden", "Mit Google fortfahren",
        "Konto erstellen", "Als Gast fortfahren",
        "Eine Abkürzung für Betreibende in die Kasse"] } },

  { shot: "cust-browse", section: "customer", portrait: true,
    en: { title: "Browsing", sub: "The marketplace",
      desc: "Every store on the platform in one list, with the filters a hungry person actually uses.",
      features: ["Delivery or Collection", "Cuisine filters from Pizza to Kebab",
        "Price filters at 20 and 30 CHF or less", "Deals",
        "Popular brands and all restaurants"] },
    de: { title: "Stöbern", sub: "Der Marktplatz",
      desc: "Alle Betriebe der Plattform in einer Liste, mit den Filtern, die hungrige Menschen wirklich benutzen.",
      features: ["Lieferung oder Abholung", "Küchenfilter von Pizza bis Kebab",
        "Preisfilter bis 20 und bis 30 CHF", "Angebote",
        "Beliebte Marken und alle Restaurants"] } },

  { shot: "cust-filter", section: "customer", portrait: true,
    en: { title: "Filtering", sub: "Narrowing it down",
      desc: "Filters apply immediately and stack, so a customer can reach the short list in two taps.",
      features: ["Filter by cuisine", "Filter by price",
        "Show all to clear", "Results update live"] },
    de: { title: "Filtern", sub: "Eingrenzen",
      desc: "Filter wirken sofort und lassen sich kombinieren, sodass die engere Auswahl in zwei Schritten erreicht ist.",
      features: ["Nach Küche filtern", "Nach Preis filtern",
        "Alle anzeigen zum Zurücksetzen", "Ergebnisse aktualisieren sich live"] } },

  { shot: "cust-collection", section: "customer", portrait: true,
    en: { title: "Collection", sub: "Picking it up",
      desc: "The same marketplace with delivery set aside, showing the stores a customer can walk to.",
      features: ["Collection instead of delivery", "No delivery fee applied",
        "Same menus and prices"] },
    de: { title: "Abholung", sub: "Selbst abholen",
      desc: "Derselbe Marktplatz ohne Lieferung, mit den Betrieben, die zu Fuss erreichbar sind.",
      features: ["Abholung statt Lieferung", "Keine Liefergebühr",
        "Gleiche Karten und Preise"] } },

  { shot: "cust-onboarding", section: "customer", portrait: true,
    en: { title: "First visit", sub: "The welcome",
      desc: "A short introduction the first time a customer opens a store, skippable in one tap.",
      features: ["Four slides", "Skip at any point", "Shown once per store"] },
    de: { title: "Erster Besuch", sub: "Die Begrüssung",
      desc: "Eine kurze Einführung beim ersten Öffnen eines Betriebs, mit einem Fingertipp überspringbar.",
      features: ["Vier Folien", "Jederzeit überspringen", "Einmal je Betrieb gezeigt"] } },

  { shot: "cust-terms", section: "customer", portrait: true,
    en: { title: "Terms", sub: "Before the first order",
      desc: "The terms are presented in full and must be accepted once. They cover orders, payment, delivery, privacy, cancellation and liability.",
      features: ["Eight numbered sections", "Explicit acceptance required",
        "Privacy policy linked", "Shown once"] },
    de: { title: "Bedingungen", sub: "Vor der ersten Bestellung",
      desc: "Die Bedingungen werden vollständig gezeigt und müssen einmal angenommen werden. Sie decken Bestellung, Zahlung, Lieferung, Datenschutz, Stornierung und Haftung ab.",
      features: ["Acht nummerierte Abschnitte", "Ausdrückliche Zustimmung nötig",
        "Datenschutzerklärung verlinkt", "Einmalig gezeigt"] } },

  { shot: "cust-menu", section: "customer", portrait: true,
    en: { title: "A store", sub: "The menu",
      desc: "The shop's own page, carrying its name, its delivery terms and its food, with search over the whole menu.",
      features: ["Delivery time, delivery fee and minimum order",
        "Delivery or Pickup", "Category shortcuts", "Popular right now",
        "Search for food or dishes", "Offers", "Cart always in reach"] },
    de: { title: "Ein Betrieb", sub: "Die Karte",
      desc: "Die eigene Seite des Betriebs mit Name, Lieferbedingungen und Speisen, samt Suche über die gesamte Karte.",
      features: ["Lieferzeit, Liefergebühr und Mindestbestellwert",
        "Lieferung oder Abholung", "Kategorie-Schnellzugriff", "Gerade beliebt",
        "Nach Speisen oder Gerichten suchen", "Angebote", "Warenkorb stets erreichbar"] } },

  { shot: "cust-item", section: "customer", portrait: true,
    en: { title: "A dish", sub: "The item sheet",
      desc: "A photograph, the description, the quantity and the price the customer will actually pay, all in one sheet.",
      features: ["Full-width photograph", "Ingredients and description",
        "Quantity up and down", "Add to cart with the running price on the button"] },
    de: { title: "Ein Gericht", sub: "Das Artikelblatt",
      desc: "Ein Foto, die Beschreibung, die Menge und der Preis, den die Kundschaft tatsächlich zahlt — alles auf einem Blatt.",
      features: ["Foto über die volle Breite", "Zutaten und Beschreibung",
        "Menge erhöhen und verringern", "In den Warenkorb mit laufendem Preis auf der Schaltfläche"] } },

  { shot: "cust-cart", section: "customer", portrait: true,
    en: { title: "The cart", sub: "Before checkout",
      desc: "What has been chosen, what it costs, and what still stands between the customer and the order.",
      features: ["Lines with quantity and price", "Delivery fee and minimum order shown",
        "Change quantities or remove", "Proceed to checkout"] },
    de: { title: "Der Warenkorb", sub: "Vor dem Bezahlen",
      desc: "Was gewählt wurde, was es kostet, und was noch zwischen Kundschaft und Bestellung steht.",
      features: ["Positionen mit Menge und Preis", "Liefergebühr und Mindestbestellwert sichtbar",
        "Mengen ändern oder entfernen", "Weiter zur Kasse"] } },
];

module.exports = { LINKS, meta, intro, sections, screens };
