#!/usr/bin/env python3
"""Builds public/brand/og-image.png — the 1200x630 link-preview card.

Typeset here rather than generated by an image model: link previews are the
first thing a prospect sees, and generated lettering is unreliable. Re-run after
any change to the logo or the tagline.
"""
import os
from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
NAVY = (4, 14, 50)
NAVY_LIFT = (11, 26, 74)
TEAL = (0, 193, 176)
WHITE = (255, 255, 255)
MUTED = (185, 195, 216)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRAND = os.path.join(ROOT, "public", "brand")

HEADLINE = "Kassenta POS"
TAGLINE_1 = "Point of sale, online ordering"
TAGLINE_2 = "and delivery in one system"
FOOTNOTE = "kassenta.com"


def load_font(size, bold=False):
    candidates = [
        r"C:\Windows\Fonts\seguisb.ttf" if bold else r"C:\Windows\Fonts\segoeui.ttf",
        r"C:\Windows\Fonts\segoeuib.ttf" if bold else r"C:\Windows\Fonts\segoeui.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for path in candidates:
        if os.path.exists(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def radial(size, centre, radius, colour, peak):
    """Soft radial glow as a standalone RGBA layer."""
    w, h = size
    layer = Image.new("L", (w // 4, h // 4), 0)
    draw = ImageDraw.Draw(layer)
    cx, cy = centre[0] // 4, centre[1] // 4
    steps = 48
    for i in range(steps, 0, -1):
        r = radius / 4 * i / steps
        alpha = int(peak * (1 - i / steps) ** 2)
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=alpha)
    layer = layer.resize((w, h), Image.LANCZOS)
    tinted = Image.new("RGBA", (w, h), colour + (0,))
    tinted.putalpha(layer)
    return tinted


def main():
    img = Image.new("RGB", (W, H), NAVY)

    # Vertical lift so the card is not a flat block of navy.
    grad = Image.new("L", (1, H))
    for y in range(H):
        grad.putpixel((0, y), int(30 * (1 - y / H)))
    img = Image.composite(Image.new("RGB", (W, H), NAVY_LIFT), img, grad.resize((W, H)))

    img = img.convert("RGBA")
    img.alpha_composite(radial((W, H), (900, 300), 520, TEAL, 70))
    img.alpha_composite(radial((W, H), (140, 620), 420, TEAL, 26))

    draw = ImageDraw.Draw(img)

    # Logo mark, top left
    mark = Image.open(os.path.join(BRAND, "logo-full-dark-bg.png")).convert("RGBA")
    target_h = 56
    mark = mark.resize((int(mark.width * target_h / mark.height), target_h), Image.LANCZOS)
    img.alpha_composite(mark, (72, 66))

    # Headline + tagline
    f_head = load_font(74, bold=True)
    f_tag = load_font(31)
    f_foot = load_font(23, bold=True)

    y = 214
    draw.text((72, y), HEADLINE, font=f_head, fill=WHITE)
    y += 104
    draw.text((72, y), TAGLINE_1, font=f_tag, fill=MUTED)
    y += 44
    draw.text((72, y), TAGLINE_2, font=f_tag, fill=MUTED)

    # Accent rule + domain
    draw.rounded_rectangle([72, 452, 268, 458], radius=3, fill=TEAL)
    draw.text((72, 486), FOOTNOTE, font=f_foot, fill=TEAL)

    out = os.path.join(BRAND, "og-image.png")
    img.convert("RGB").save(out, "PNG", optimize=True)
    print(f"wrote {out} ({os.path.getsize(out) // 1024} KB)")


if __name__ == "__main__":
    main()
